<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pack.proto

namespace Pack\Base;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pack.base.LoginRsp</code>
 */
class LoginRsp extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 uid = 1;</code>
     */
    protected $uid = 0;
    /**
     * Generated from protobuf field <code>.pack.base.LoginType login_type = 2;</code>
     */
    protected $login_type = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $uid
     *     @type int $login_type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Pack::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 uid = 1;</code>
     * @return int
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * Generated from protobuf field <code>int32 uid = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setUid($var)
    {
        GPBUtil::checkInt32($var);
        $this->uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pack.base.LoginType login_type = 2;</code>
     * @return int
     */
    public function getLoginType()
    {
        return $this->login_type;
    }

    /**
     * Generated from protobuf field <code>.pack.base.LoginType login_type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setLoginType($var)
    {
        GPBUtil::checkEnum($var, \Pack\Base\LoginType::class);
        $this->login_type = $var;

        return $this;
    }

}

